### ISSUE TITLE
Add infinity horizon

### ISSUE THREAD

**Issue by Thiago-NovaesB** [LAMPSPUC/HydroPowerModels.jl#13]
Alternative to the option of setting a minimum final volume to avoid the complete emptying of the reservoirs at the end of the horizon.

https://sddp.dev/dev/explanation/theory_intro/#Example:-infinite-horizon

**Comment by odow** [comment]
Here's a better link: https://sddp.dev/dev/tutorial/example_reservoir/#Cyclic-graphs
